/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package effekseer.swig;

public class EffekseerNodeCore {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected EffekseerNodeCore(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EffekseerNodeCore obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
  }

  public EffekseerNodeCore getChild(int index) {
    long cPtr = EffekseerCoreJNI.EffekseerNodeCore_getChild(swigCPtr, this, index);
    return (cPtr == 0) ? null : new EffekseerNodeCore(cPtr, false);
  }

  public int getChildCount() {
    return EffekseerCoreJNI.EffekseerNodeCore_getChildCount(swigCPtr, this);
  }

  public void setVisibility(boolean visible) {
    EffekseerCoreJNI.EffekseerNodeCore_setVisibility(swigCPtr, this, visible);
  }

  public void setParameterCommonValues(float[] t) {
    EffekseerCoreJNI.EffekseerNodeCore_setParameterCommonValues(swigCPtr, this, t);
  }

  public void setGeneration(float[] t) {
    EffekseerCoreJNI.EffekseerNodeCore_setGeneration(swigCPtr, this, t);
  }

  public void setGenerationPoint(float[] t) {
    EffekseerCoreJNI.EffekseerNodeCore_setGenerationPoint(swigCPtr, this, t);
  }

  public void setGenerationLine(float[] t) {
    EffekseerCoreJNI.EffekseerNodeCore_setGenerationLine(swigCPtr, this, t);
  }

  public void setGenerationCircle(float[] t) {
    EffekseerCoreJNI.EffekseerNodeCore_setGenerationCircle(swigCPtr, this, t);
  }

  public void setGenerationSphere(float[] t) {
    EffekseerCoreJNI.EffekseerNodeCore_setGenerationSphere(swigCPtr, this, t);
  }

  public void setGenerationModel(float[] t) {
    EffekseerCoreJNI.EffekseerNodeCore_setGenerationModel(swigCPtr, this, t);
  }

  public int getTranslationType() {
    return EffekseerCoreJNI.EffekseerNodeCore_getTranslationType(swigCPtr, this);
  }

  public void setTranslationType(int type) {
    EffekseerCoreJNI.EffekseerNodeCore_setTranslationType(swigCPtr, this, type);
  }

  public FloatArray getTranslationFixed() {
    return new FloatArray(EffekseerCoreJNI.EffekseerNodeCore_getTranslationFixed(swigCPtr, this), true);
  }

  public void setTranslationFixed(float[] values) {
    EffekseerCoreJNI.EffekseerNodeCore_setTranslationFixed(swigCPtr, this, values);
  }

  public FloatArray getTranslationPVA() {
    return new FloatArray(EffekseerCoreJNI.EffekseerNodeCore_getTranslationPVA(swigCPtr, this), true);
  }

  public void setTranslationPVA(float[] values) {
    EffekseerCoreJNI.EffekseerNodeCore_setTranslationPVA(swigCPtr, this, values);
  }

  public FloatArray getTranslationEasing() {
    return new FloatArray(EffekseerCoreJNI.EffekseerNodeCore_getTranslationEasing(swigCPtr, this), true);
  }

  public void setTranslationEasing(float[] values) {
    EffekseerCoreJNI.EffekseerNodeCore_setTranslationEasing(swigCPtr, this, values);
  }

  public int getRotationType() {
    return EffekseerCoreJNI.EffekseerNodeCore_getRotationType(swigCPtr, this);
  }

  public void setRotationType(int type) {
    EffekseerCoreJNI.EffekseerNodeCore_setRotationType(swigCPtr, this, type);
  }

  public void setRotationFixed(float[] values) {
    EffekseerCoreJNI.EffekseerNodeCore_setRotationFixed(swigCPtr, this, values);
  }

  public void setRotationPVA(float[] values) {
    EffekseerCoreJNI.EffekseerNodeCore_setRotationPVA(swigCPtr, this, values);
  }

  public void setRotationEasing(float[] values) {
    EffekseerCoreJNI.EffekseerNodeCore_setRotationEasing(swigCPtr, this, values);
  }

  public int getScalingType() {
    return EffekseerCoreJNI.EffekseerNodeCore_getScalingType(swigCPtr, this);
  }

  public void setScalingType(int type) {
    EffekseerCoreJNI.EffekseerNodeCore_setScalingType(swigCPtr, this, type);
  }

  public void setScalingFixed(float[] values) {
    EffekseerCoreJNI.EffekseerNodeCore_setScalingFixed(swigCPtr, this, values);
  }

  public void setScalingPVA(float[] values) {
    EffekseerCoreJNI.EffekseerNodeCore_setScalingPVA(swigCPtr, this, values);
  }

  public void setScalingEasing(float[] values) {
    EffekseerCoreJNI.EffekseerNodeCore_setScalingEasing(swigCPtr, this, values);
  }

  public void setBasicRenderSettings(float[] t) {
    EffekseerCoreJNI.EffekseerNodeCore_setBasicRenderSettings(swigCPtr, this, t);
  }

  public void setBasicRenderSettingsMaterialDefault(float[] t) {
    EffekseerCoreJNI.EffekseerNodeCore_setBasicRenderSettingsMaterialDefault(swigCPtr, this, t);
  }

  public void setBasicRenderSettingsMaterialDistortion(float[] t) {
    EffekseerCoreJNI.EffekseerNodeCore_setBasicRenderSettingsMaterialDistortion(swigCPtr, this, t);
  }

  public void setBasicRenderSettingsMaterialLighting(float[] t) {
    EffekseerCoreJNI.EffekseerNodeCore_setBasicRenderSettingsMaterialLighting(swigCPtr, this, t);
  }

  public void setBasicRenderSettingsMaterialFile(float[] t) {
    EffekseerCoreJNI.EffekseerNodeCore_setBasicRenderSettingsMaterialFile(swigCPtr, this, t);
  }

  public void setRenderSettings(float[] t) {
    EffekseerCoreJNI.EffekseerNodeCore_setRenderSettings(swigCPtr, this, t);
  }

  public void setRenderSettingsNone(float[] t) {
    EffekseerCoreJNI.EffekseerNodeCore_setRenderSettingsNone(swigCPtr, this, t);
  }

  public void setRenderSettingsSprite(float[] t) {
    EffekseerCoreJNI.EffekseerNodeCore_setRenderSettingsSprite(swigCPtr, this, t);
  }

  public void setRenderSettingsTrack(float[] t) {
    EffekseerCoreJNI.EffekseerNodeCore_setRenderSettingsTrack(swigCPtr, this, t);
  }

  public void setRenderSettingsRibbon(float[] t) {
    EffekseerCoreJNI.EffekseerNodeCore_setRenderSettingsRibbon(swigCPtr, this, t);
  }

  public void setRenderSettingsRing(float[] t) {
    EffekseerCoreJNI.EffekseerNodeCore_setRenderSettingsRing(swigCPtr, this, t);
  }

  public void setRenderSettingsModel(float[] t) {
    EffekseerCoreJNI.EffekseerNodeCore_setRenderSettingsModel(swigCPtr, this, t);
  }

  public void setRenderSettings_ColorAll(float[] t) {
    EffekseerCoreJNI.EffekseerNodeCore_setRenderSettings_ColorAll(swigCPtr, this, t);
  }

}
