/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package effekseer.swig;

public class EffekseerNodeCore {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected EffekseerNodeCore(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EffekseerNodeCore obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
  }

  public EffekseerNodeCore getChild(int index) {
    long cPtr = EffekseerCoreJNI.EffekseerNodeCore_getChild(swigCPtr, this, index);
    return (cPtr == 0) ? null : new EffekseerNodeCore(cPtr, false);
  }

  public int getChildCount() {
    return EffekseerCoreJNI.EffekseerNodeCore_getChildCount(swigCPtr, this);
  }

  public int getTranslationType() {
    return EffekseerCoreJNI.EffekseerNodeCore_getTranslationType(swigCPtr, this);
  }

  public void setTranslationType(int type) {
    EffekseerCoreJNI.EffekseerNodeCore_setTranslationType(swigCPtr, this, type);
  }

  public FloatArray getTranslationFixed() {
    return new FloatArray(EffekseerCoreJNI.EffekseerNodeCore_getTranslationFixed(swigCPtr, this), true);
  }

  public void setTranslationFixed(float[] values) {
    EffekseerCoreJNI.EffekseerNodeCore_setTranslationFixed(swigCPtr, this, values);
  }

  public FloatArray getTranslationPVA() {
    return new FloatArray(EffekseerCoreJNI.EffekseerNodeCore_getTranslationPVA(swigCPtr, this), true);
  }

  public void setTranslationPVA(float[] values) {
    EffekseerCoreJNI.EffekseerNodeCore_setTranslationPVA(swigCPtr, this, values);
  }

  public FloatArray getTranslationEasing() {
    return new FloatArray(EffekseerCoreJNI.EffekseerNodeCore_getTranslationEasing(swigCPtr, this), true);
  }

  public void setTranslationEasing(float[] values) {
    EffekseerCoreJNI.EffekseerNodeCore_setTranslationEasing(swigCPtr, this, values);
  }

}
