/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package effekseer.swig;

public class FloatArray {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FloatArray(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FloatArray obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        EffekseerCoreJNI.delete_FloatArray(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setValues(float[] value) {
    EffekseerCoreJNI.FloatArray_values_set(swigCPtr, this, value);
  }

  public float[] getValues() {
    return EffekseerCoreJNI.FloatArray_values_get(swigCPtr, this);
  }

  public FloatArray() {
    this(EffekseerCoreJNI.new_FloatArray(), true);
  }

}
